# Generated by Django 3.1.5 on 2021-01-08 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_biblioteka', '0002_auto_20210108_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=32),
        ),
    ]
